### ISSUE TITLE
No token images for common bases

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap-interface#13]
Token images are not displayed when shown under common bases

https://prnt.sc/10bs6fq

**Comment by matthewlilley** [comment]
Related to getTokenLogoURL functions which were designed for mainnet only.

https://github.com/sushiswap/sushiswap-interface/blob/master/src/components/CurrencyLogo/index.tsx#L72

**Comment by matthewlilley** [comment]
Example: https://github.com/VenomProtocol/venomswap-interface/blob/main/src/components/CurrencyLogo/index.tsx

**Comment by seansean11** [comment]
Any update on this one?  I finally have some free time and am looking to pick up some issues.

**Comment by matthewlilley** [comment]
Hey @seansean11,

No work on this ATM so feel free to jump on it. Images should already be available on the token lists for any chain, so just some re-plumbing required.

**Comment by seansean11** [comment]
@matthewlilley I looked into this issue a bit and see that MATIC and BSC base logos are being taken care of via mappings from the `getTokenLogoURL`, so that screenshot of missing BSC have already been filled in.  I do see that bases are missing for other chains though (Fantom, OKEx, Harmony, etc...).  The example you linked to from Venom Protocol seems to use image fallbacks of their own assets via CloudFront signed URL's.   I could either create more mappings for tokens in `getTokenLogoURL` or figure out a way to pass the base currencies as WrappedTokenInfo instead of Token.  Let me know if you have a preference.
