### ISSUE TITLE
Please add incentivized yield farms and sushibar/xsushi on [FANTOM] chain

### ISSUE THREAD

**Issue by mmmmyah** [sushiswap/sushiswap-interface#137]
There are no incentivized yield farms at the moment on Fantom. Staking sushi for xsushi only works on Mainnet currently. 

Please add yield farms and sushibar on the Fantom chain. It seems like only Sushi Swap works on Fantom. I can't find the Yield and Sushibar top navigation bar items (like I do on ethereum) and the following URLs just redirect to swap ..
https://app.sushi.com/yield
https://app.sushi.com/sushibar

Getting a lot of requests for sushi farms on Fantom .. please add!!! thanks!!!!

**Comment by omakasebar** [comment]
@mmmmyah tagging as an operational request. Since this is not related to the interface or existing features would be happy for you to provide more details or I will close this issue.

For example, 
A) Which pairs do you think should be incentivized on Fantom initially? 
B) Which Fantom specific projects should we keep an eye out for in order to attract more organic community participation?
C) What projects are current competing yield farms on Fantom and what do their APY and liquidity look like?
D) How many sushi rewards would be required to stay competitive assuming similar liquidity to question C)?

Operational requests require a bit more homework to open discussions - thanks!

**Comment by omakasebar** [comment]
Closing due to going stale
