### ISSUE TITLE
Refactor i18next to lingui

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#79]
Pros using lingui: 
- you don't have to use hooks (useTranslation) to rerender static text. Instead the contextprovider will load a new catalog.
- using package @lingui/cli can easily extract messages in different formats like for example .po file
- crowdin-github integration with husky in npm. Use a pre-commit hook to extract translations from the code. Crowdin will poll these changes and flag them in their UI for translators to translate. Once translated crowdin can create a PR on the UI

Cons using lingui:
- Requires rewrite of current locale system

Cons of i18next:
- Cannot properly handle special characters

Lingui solution uses 3 packages:
- Lingui uses @lingui/react, @lingui/cli, @lingui/detect-locale

i18next uses 5 packages:
- @babel/cli, @babel/preset-typescript, babel-plugin-i18next-extract, i18next, i18next-browser-languagedetector

**Comment by chillichelli** [comment]
I think we should use [Lokalise](https://lokalise.com) to automate our localization flow.  We can either use one of their plans to have them translate it for us but as we have a lot of DeFi terms, I suggest we add our own translators to the team created on lokalise.com. It seems easy to set up a Github integration as well. It requires a personal access token that can read and create MRs.

This MR will replace react-i18next in favour of @Lingui because of the cons mentioned by @omakasebar. I noticed a lot of translations are missing or incomplete so I didn't dare entering translations that weren't 1 on 1.

All in all: this is how I imagine the flow
1. When a developer encounters plain text in code, he/she should wrap it with `import { t } from @lingui/macro` such that `Connect wallet` becomes ``{t`Connect wallet`}``
2. A Husky pre-commit hook has been applied that runs `yarn extract && yarn compile` pre-commit to make sure the repo always contains all extracted and compiled keys
3. Lokalise will poll our localization files from Github and flags new keys for translators to translate
4. Once we have enough new keys we can inform translators there are new keys to translate
5. Once translators have translated new keys Lokalise will create a MR on the repo

If we don't want Github integration, we can drop step 3 and 5 and upload/download files manually like we currently do. In any case, I really think we should use Lokalise instead of a Google Doc to avoid errors and missing translations

**Comment by chillichelli** [comment]
I ported the google doc to lokalise.com. I figured the keys in the google doc are the most important ones so I prepared those in the code first. There is still a lot of plain text left but I guess we'll have to change that iteratively. 

Missing translations for Chinese Simplified and Chinese Traditional are being worked on as i'm typing this. Once those are ready, I will push the new translation files to my PR.
